# Generated by Django 5.2.1 on 2025-05-24 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('moderator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('data_prevista', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('data_devolvida', models.DateTimeField(blank=True, null=True)),
                ('devolvido', models.BooleanField(default=False)),
                ('devolução_confirmada', models.BooleanField(default=False)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moderator.material')),
                ('quem_aprovou', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aprovou_o_pedido', to='accounts.userprofile')),
                ('usuário', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='aluno', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
